### ISSUE TITLE
标题里的MathJax显示不正常

### ISSUE THREAD

**Issue by zhaojinxiang** [leanote/leanote#124]
在markdown里编辑
```markdown
#用Monte Carlo method计算$\pi$
```
发布到博客，得到的结果是标题的MathJax公式太小，和普通文本一样大
结果是显示由css的
```css
#content * {
  font-size: 16px;
}
```
控制了MathJax的显示

可以直接删除了这个css属性（反正默认的字体大小也差不多能看了……）

但是调整了字体，要注意调整其它部分的东西啊，否则就难看了，比如`pre.prettyprint`的` padding`
