### ISSUE TITLE
Run leanote in docker - Updated instructions - Fixes Connection reset error.

### ISSUE THREAD

**Issue by adrianharabula** [leanote/leanote#735]
Following wiki page [Run Leanote by docker](https://github.com/leanote/leanote/wiki/Run-leanote-by-docker) I was not able to run leanote.

The app won't run, you will get a connection reset when trying to connect to http://localhost:9000.

Also in the instructions provided, mongodb is not initialized with the leanote schema.

I have updated the process to make leanote run in docker:

1. Download latest leanote binary (tried with the 2.6).
2. Unzip the binaries, somewhere.
3. On project root, create `docker-compose.yml` with the following:
```yml
version: '2'

services:
  db:
    image: mongo:3.6
    restart: always
    volumes:
      - ./mongodb_backup:/docker-entrypoint-initdb.d/
      - ./database:/data/db

  server:
    image: ubuntu:xenial
    restart: always
    depends_on:
      - db
    links:
      - db
    working_dir: /usr/local/leanote/bin
    entrypoint:
      - sh
      - run.sh
    ports:
     - "9000:9000"
    volumes:
      - "./:/usr/local/leanote"

```
4. Create `mongo-init.sh` in [mongodb_backup](https://github.com/leanote/leanote/tree/master/mongodb_backup) containing:
```bash
#!/usr/bin
mongorestore -h localhost -d leanote --dir /docker-entrypoint-initdb.d/leanote_install_data/
```
5. Update [conf/app.conf](https://github.com/leanote/leanote/blob/master/conf/app.conf), double check the following:
   * `http.port=9000`
   * `site.url=http://localhost:9000`
   * `db.host=db` - change to `db`!!!
   * `app.secret=` - change with something random, generate random string with `openssl rand -base64 32`
   * `http.addr=0.0.0.0` - be sure to set it to 0.0.0.0, this fixes the Connection reset error!!!
6. Run leanote app with `docker-compose up -d` in project root. Database will be initialized with leanote data. App will start immediately afterwards.

Visit [http://localhost:9000](http://localhost:9000).
